version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 81:80
    volumes:
      - ./lb-nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx-network

  fastAPIApp1:
    image: fastapiapp1
    networks:
      - nginx-network

  fastAPIApp2:
    image: fastapiapp2
    networks:
      - nginx-network

networks:
  nginx-network:
    external:
      name: nginx-network
